addpath(pwd);
addpath([pwd '/knnsearch']);
addpath([pwd '/count_unique']);
%addpath([pwd '/matmex']);
addpath(genpath('/home/bobye/pub/drtoolbox'));
%addpath('/home/bobye/pub/BoostMetric-v0.1');
%addpath([pwd '/mtrees']);
global RootPath BoostPath LMNNPath;
RootPath = pwd;
BoostPath = '/home/bobye/pub/BoostMetric-v0.1';
LMNNPath = '/home/bobye/Dropbox/code/CFLML2';